set(SOURCES
	src/Main.cpp
	src/Window.cpp
	src/WindowsMessageMap.cpp
	src/ImGuiRenderer.cpp
	src/ImGuiElement.cpp
	src/UI.cpp
	include/PCH.h
	include/Window.h
	include/WindowsMessageMap.h
	include/ImGuiRenderer.h
	include/ImGuiElement.h
	include/UI.h
)
